### ISSUE TITLE
v13 Asynchronous 400 Error 

### ISSUE THREAD

**Issue by ly11tea** [miguelgrinberg/flack#3]
i have followed the code in V13,which implements async decorator.but in the usage,i found the" post new message" route keep returning  400 Error,except the very beginning few Requests .
the 400 error is arised by` request.get_json()` in the route function where :
```
@api.route('/messages', methods=['POST'])
@token_auth.login_required
@async
def new_message():
    """
    Post a new message.
    This endpoint is requires a valid user token.
    """
    msg = Message.create(request.get_json() or {})
    db.session.add(msg)
    db.session.commit()
    r = jsonify(msg.to_dict())
    r.status_code = 201
    r.headers['Location'] = url_for('api.get_message', id=msg.id)
    return r
```
since the request context is faked by async decorator ,i keep looking  up into it, i found the ` request.environ['wsgi.input'] (a file object) has been closed between  passing  the request to the thread  function where:
```
        thread = threading.Thread(target=task,
                                  args=[current_app._get_current_object(), request.environ, g.current_user.nickname])
```
and in the thread function where:
```
with app.request_context(environ):
                print environ['wsgi.input']
                print request.get_json()
                current_user = User.query.filter_by(nickname=name).first()
                if current_user is None:
                    raise RuntimeError('invalid user')
                g.current_user = current_user
                try:
                    tasks[id]['rv'] = f(*args, **kwargs)
                except HTTPException as e:
                    tasks[id]['rv'] = current_app.handle_http_exception(e)
                except Exception as e:
                    tasks[id]['rv'] = InternalServerError()
                    if current_app.debug:
                        raise
                finally:
                    tasks[id]['t'] = timestamp()
                db.session.remove()
```
in the condition which is successful ,the request.environ['wsgi.input'] (a file object) are both open
`<open file '<socket>', mode 'rb' at 0xb66cb910>
`
while in the failure condition, the request.environ['wsgi.input'] is
`<open file '<socket>', mode 'rb' at 0xb49c51d8>`when passing parameters,
but in  the thread function it  is:`<closed file '<socket>', mode 'rb' at 0xb49c51d8>` and obviously i can't read the content in it,since it is closed. 

is this the cause of the 400 error,any advice on that?,thank you !
by the way ,i have completely used your code and change nothing,but get same result.

**Comment by miguelgrinberg** [comment]
I don't remember the wsgi.input handle ever being closed, but that could be due to you using different (likely newer) versions of Flask and Werkzeug.

In any case, the correct way to handle this is to set a new handle, to ensure that the async task can always read. Something like this:

    environ['wsgi.input'] = BytesIO(request.get_data())

**Comment by ly11tea** [comment]
thank you !

**Comment by miguelgrinberg** [comment]
This is now addressed. Thanks!
