### ISSUE TITLE
Don't listen on 0.0.0.0 when behind a load balancer

### ISSUE THREAD

**Issue by stefaang** [miguelgrinberg/flack#5]
Minor documentation recommendation:
I'd add a remark in the webserver init scripts to bind to localhost (127.0.0.1) instead of 0.0.0.0 when using a load balancer like nginx. It's handy in the testing phase but not recommended in production.
Or am I missing something here?

**Comment by miguelgrinberg** [comment]
Yes, that's actually a good recommendation.

**Comment by miguelgrinberg** [comment]
I have updated all the gunicorn/uwsgi scripts to start on 127.0.0.1. Thanks!
