### ISSUE TITLE
uWSGI Relative Import Error

### ISSUE THREAD

**Issue by johnrbnsn** [miguelgrinberg/flack#6]
Hi Miguel,

I cloned your repo and tried running the uWSGI script (I ctrl-c/ctrl-v'd it in the command line).  I'm running Ubuntu 16.04, and I've included all my steps (from cloning onward) below, as well as the error message.  Any idea where I went wrong?

    jr@laptop:~/Desktop$ git clone https://github.com/miguelgrinberg/flack.git
    ... response ...
    jr@laptop:~/Desktop$ cd flack/
    jr@laptop:~/Desktop/flack$ python3 -m venv venv
    jr@laptop:~/Desktop/flack$ source venv/bin/activate
    (venv) jr@laptop:~/Desktop/flack$ pip install -r requirements.txt 
    ... response ...

Error when running uwsgi:

    (venv) jr@laptop:~/Desktop/flack$ venv/bin/uwsgi --http 127.0.0.1:5000 --wsgi-file flack/wsgi.py
    *** Starting uWSGI 2.0.12 (64bit) on [Wed Feb  8 17:36:25 2017] ***
    compiled with version: 5.4.0 20160609 on 08 February 2017 17:31:44
    os: Linux-4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017
    nodename: jr-laptop
    machine: x86_64
    clock source: unix
    detected number of CPU cores: 4
    current working directory: /home/jr/Desktop/flack
    detected binary path: /home/jr/Desktop/flack/venv/bin/uwsgi
    !!! no internal routing support, rebuild with pcre support !!!
    *** WARNING: you are running uWSGI without its master process manager ***
    your processes number limit is 15097
    your memory page size is 4096 bytes
    detected max file descriptor number: 1024
    lock engine: pthread robust mutexes
    thunder lock: disabled (you can enable it with --thunder-lock)
    uWSGI http bound on 127.0.0.1:5000 fd 4
    spawned uWSGI http 1 (pid: 7837)
    uwsgi socket 0 bound to TCP address 127.0.0.1:41406 (port auto-assigned) fd 3
    Python version: 3.5.2 (default, Nov 17 2016, 17:05:23)  [GCC 5.4.0 20160609]
    *** Python threads support is disabled. You can enable it with --enable-threads ***
    Python main interpreter initialized at 0x246b800
    your server socket listen backlog is limited to 100 connections
    your mercy for graceful operations on workers is 60 seconds
    mapped 72768 bytes (71 KB) for 1 cores
    *** Operational MODE: single process ***
    Traceback (most recent call last):
    File "flack/wsgi.py", line 3, in <module>
        from . import create_app
    SystemError: Parent module '' not loaded, cannot perform relative import
    unable to load app 0 (mountpoint='') (callable not found or import error)
    *** no app loaded. going in full dynamic mode ***
    *** uWSGI is running in multiple interpreter mode ***
    spawned uWSGI worker 1 (and the only) (pid: 7836, cores: 1)

Any idea on where I went wrong?  I understand it doesn't like something with my import path, but I'm not sure how to fix it.  Thanks for making this tutorial, I've learned a ton about Flask from you! 

--JR

----------------------------------------------------------------------------------------------------------------------------

Error: 

    Traceback (most recent call last):
    File "flack/wsgi.py", line 3, in <module>
        from . import create_app
    SystemError: Parent module '' not loaded, cannot perform relative import
    unable to load app 0 (mountpoint='') (callable not found or import error)

File Permissions (in case that's helpful) subdirectories also owned by jr jr:

    (venv) jr@laptop:~/Desktop/flack$ ls -la
    drwxrwxr-x 8 jr jr 4096 Feb  8 17:29 .
    drwxr-xr-x 3 jr jr 4096 Feb  8 17:29 ..
    -rw-rw-r-- 1 jr jr 1064 Feb  8 17:29 config.py
    drwxrwxr-x 5 jr jr 4096 Feb  8 17:29 flack
    drwxrwxr-x 8 jr jr 4096 Feb  8 17:29 .git
    -rw-rw-r-- 1 jr jr  406 Feb  8 17:29 .gitignore
    -rw-rw-r-- 1 jr jr 1076 Feb  8 17:29 LICENSE
    -rwxrwxr-x 1 jr jr 3418 Feb  8 17:29 manage.py
    -rw-rw-r-- 1 jr jr 2473 Feb  8 17:29 README.md
    -rw-rw-r-- 1 jr jr  688 Feb  8 17:29 requirements.txt
    drwxrwxr-x 2 jr jr 4096 Feb  8 17:29 scripts
    drwxrwxr-x 2 jr jr 4096 Feb  8 17:29 tests
    drwxrwxr-x 6 jr jr 4096 Feb  8 17:31 venv
    drwxrwxr-x 3 jr jr 4096 Feb  8 17:29 webserver

**Comment by stefaang** [comment]
I think you should stick to the manage.py script, even for production.
```
export FLACK_CONFIG=production
python manage.py runserver
```
Works for me.

**Comment by miguelgrinberg** [comment]
@johnrbnsn Hmmm, not sure how this worked for me in the past. I have updated the wsgi script to not use relative imports, that is not a good idea for an entry point script anyway. Clone the repo again and you will get the updated version.
