### ISSUE TITLE
got error when using asynchronous tasks

### ISSUE THREAD

**Issue by xilixjd** [miguelgrinberg/flack#7]
I used your asynchronous tasks in my project.
This is the error log from celery:

```
[2017-04-01 01:16:55,942: ERROR/PoolWorker-3] Task webapp.tasks.run_flask_request[f1cd8a5e-a4d6-4737-8272-2ac18b437a12] raised unexpected: TypeError("'unicode' does not have the buffer interface",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/xilixjd/Desktop/python_react_blog1/python_react_blog_back_end/webapp/tasks.py", line 29, in run_flask_request
    environ['wsgi.input'] = BytesIO(environ['_wsgi.input'])
TypeError: 'unicode' does not have the buffer interface
```

And i called like this:

```
@app_blueprint.route('/send')
@async
def send():
    time.sleep(10)
    return "send email"
```

when i go to '/send', then the error on the top showed

btw:
I am using python 2.7.13 and Werkzeug==0.12.1

**Comment by miguelgrinberg** [comment]
The contents of `environ['_wsgi.input']` should have been of type `str` or `bytes`, but in your case it appears it is a `unicode` value. You may want to debug this by checking when this value is assigned to `request.get_data()`.

**Comment by xilixjd** [comment]
Thanks for reply.
The problem is still unsolved.
i print request.environ in async funcition
```
def async(f):
    @wraps(f)
    def wrapped(*args, **kwargs):
    ...
    print request.environ
    ...
```
the result:

> {'wsgi.multiprocess': False, 'HTTP_COOKIE': 'csrftoken=4oI0kDxE9GvZSbBDgO3CjYBtXULBHTZn; _ga=GA1.1.282166179.1463715517; remember_token=1|49049835490366078e1b2e0b15bbb50e19b8754f07f972c2140713159e35b58842624353226cd01839928643c5afb86c7a64e3f13589c4df1ea1c3c9b27ff817; session=eyJlbWFpbCI6InhpbGl4amRAMTYzLmNvbSJ9.C77A1w.lH4qkmqwu3w8cO02STYmIolSvCk', 'SERVER_SOFTWARE': 'Werkzeug/0.12.1', 'SCRIPT_NAME': '', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/send', 'SERVER_PROTOCOL': 'HTTP/1.1', 'QUERY_STRING': '', 'werkzeug.server.shutdown': <function shutdown_server at 0x102adb500>, 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36', 'HTTP_CONNECTION': 'keep-alive', 'SERVER_NAME': '0.0.0.0', 'REMOTE_PORT': 64995, 'wsgi.url_scheme': 'http', 'SERVER_PORT': '5000', 'werkzeug.request': <Request 'http://127.0.0.1:5000/send' [GET]>, 'wsgi.input': <open file '<socket>', mode 'rb' at 0x1029d19c0>, 'HTTP_HOST': '127.0.0.1:5000', 'wsgi.multithread': False, 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_CACHE_CONTROL': 'max-age=0', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x100a951e0>, 'REMOTE_ADDR': '127.0.0.1', 'HTTP_ACCEPT_LANGUAGE': 'zh-CN,zh;q=0.8,en;q=0.6', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch, br'}


and print environ in run_flask_request

```
@celery.task
def run_flask_request(environ):
    from .celery_worker import app
    print environ
    ...
```

result:

> {u'HTTP_ACCEPT': u'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', u'HTTP_USER_AGENT': u'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36', u'HTTP_CONNECTION': u'keep-alive', u'SERVER_NAME': u'0.0.0.0', u'HTTP_COOKIE': u'csrftoken=4oI0kDxE9GvZSbBDgO3CjYBtXULBHTZn; _ga=GA1.1.282166179.1463715517; remember_token=1|49049835490366078e1b2e0b15bbb50e19b8754f07f972c2140713159e35b58842624353226cd01839928643c5afb86c7a64e3f13589c4df1ea1c3c9b27ff817; session=eyJlbWFpbCI6InhpbGl4amRAMTYzLmNvbSJ9.C77A1w.lH4qkmqwu3w8cO02STYmIolSvCk', u'REMOTE_ADDR': u'127.0.0.1', u'SERVER_SOFTWARE': u'Werkzeug/0.12.1', u'HTTP_ACCEPT_LANGUAGE': u'zh-CN,zh;q=0.8,en;q=0.6', u'SCRIPT_NAME': u'', u'wsgi.url_scheme': u'http', u'REQUEST_METHOD': u'GET', u'HTTP_HOST': u'127.0.0.1:5000', u'PATH_INFO': u'/send', u'SERVER_PORT': u'5000', u'SERVER_PROTOCOL': u'HTTP/1.1', u'QUERY_STRING': u'', u'HTTP_UPGRADE_INSECURE_REQUESTS': u'1', u'_wsgi.input': u'', u'HTTP_CACHE_CONTROL': u'max-age=0', u'HTTP_ACCEPT_ENCODING': u'gzip, deflate, sdch, br'}

the value of request.environ in your repository:
> {'wsgi.multiprocess': False, 'HTTP_COOKIE': 'csrftoken=4oI0kDxE9GvZSbBDgO3CjYBtXULBHTZn; _ga=GA1.1.282166179.1463715517; remember_token=1|49049835490366078e1b2e0b15bbb50e19b8754f07f972c2140713159e35b58842624353226cd01839928643c5afb86c7a64e3f13589c4df1ea1c3c9b27ff817; session=eyJlbWFpbCI6InhpbGl4amRAMTYzLmNvbSJ9.C77A1w.lH4qkmqwu3w8cO02STYmIolSvCk', 'SERVER_SOFTWARE': 'Werkzeug/0.12.1', 'SCRIPT_NAME': '', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/api/messages', 'SERVER_PROTOCOL': 'HTTP/1.1', 'QUERY_STRING': '', 'werkzeug.server.shutdown': <function shutdown_server at 0x1101845f0>, 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36', 'HTTP_CONNECTION': 'keep-alive', 'SERVER_NAME': '127.0.0.1', 'REMOTE_PORT': 65123, 'wsgi.url_scheme': 'http', 'SERVER_PORT': '5000', 'werkzeug.request': <Request 'http://127.0.0.1:5000/api/messages' [GET]>, 'wsgi.input': <socket._fileobject object at 0x1101b1cd0>, 'HTTP_HOST': '127.0.0.1:5000', 'wsgi.multithread': False, 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_CACHE_CONTROL': 'max-age=0', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x10e3891e0>, 'REMOTE_ADDR': '127.0.0.1', 'HTTP_ACCEPT_LANGUAGE': 'zh-CN,zh;q=0.8,en;q=0.6', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch, br'}

the value of environ in your repository:
> {'_wsgi.input': '', 'HTTP_COOKIE': 'csrftoken=4oI0kDxE9GvZSbBDgO3CjYBtXULBHTZn; _ga=GA1.1.282166179.1463715517; remember_token=1|49049835490366078e1b2e0b15bbb50e19b8754f07f972c2140713159e35b58842624353226cd01839928643c5afb86c7a64e3f13589c4df1ea1c3c9b27ff817; session=eyJlbWFpbCI6InhpbGl4amRAMTYzLmNvbSJ9.C77A1w.lH4qkmqwu3w8cO02STYmIolSvCk', 'SERVER_SOFTWARE': 'Werkzeug/0.12.1', 'SCRIPT_NAME': '', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/api/messages', 'SERVER_PROTOCOL': 'HTTP/1.1', 'QUERY_STRING': '', 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36', 'HTTP_CONNECTION': 'keep-alive', 'SERVER_NAME': '127.0.0.1', 'REMOTE_ADDR': '127.0.0.1', 'wsgi.url_scheme': 'http', 'SERVER_PORT': '5000', 'werkzeug.request': <Request 'http://127.0.0.1:5000/api/messages' [GET]>, 'wsgi.input': <_io.BytesIO object at 0x1094b6dd0>, 'HTTP_HOST': '127.0.0.1:5000', 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_CACHE_CONTROL': 'max-age=0', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'HTTP_ACCEPT_LANGUAGE': 'zh-CN,zh;q=0.8,en;q=0.6', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch, br'}

**Comment by miguelgrinberg** [comment]
I think I may know what's going on. New versions of Celery use JSON as the default format for transferring data between the client and the celery worker. Back when I did this project, Celery defaulted to pickle as transfer mechanism. I think the JSON transfer is converting all your `str` to `unicode`. Can you try using the Celery version I have in my requirements file to confirm it works with the version?

If that's the case, in the meantime you can switch to the old release. To solve the problem definitely you need to convert the unicode back to str/bytes, using the `encode('utf-8')` method.

**Comment by xilixjd** [comment]
I followed your advice, uninstall celery 4, install celery 3.1, the problem has been solved.
That's actually the case u said.

And do u mean, i have to change the environ variable's all the key and value in run_flask_request function to 'str' ?

Really appreciate for your help and your repository and blog help me a lot.

**Comment by martintamare** [comment]
I'm curious on how to unit_test this error. Any clue ?

**Comment by miguelgrinberg** [comment]
@martintamare You have to consider that there is really no "error" per se. The requirements.txt file includes the version of Celery that was tested and verified to work. The application makes assumptions that stopped being true in Celery versions 4 and up, so the only way to experience problems is if you decide to bump the Celery version in the requirements. Just to give you an example, I'm running this application at flack.miguelgrinberg.com and it has absolutely no problem, because the requirements save me from using the incompatible versions of Celery.

Now, if you want to upgrade Celery to the latest 4.x release, then the application needs to be updated as well. The default marshaling mechanism in Celery 4 is JSON (it was pickle in the 3.x releases), so now anything you send over to the Celery workers needs to be translatable to JSON. You can update the application to work with Celery 4, and then if you want, you can add a unit test that ensures that the arguments sent in the call to the Celery task can be jsonified. You do not need to invoke the task or have Celery running, just replace the task with a mock, capture the arguments and apply JSON to them ensuring there are no exceptions raised.

**Comment by miguelgrinberg** [comment]
Re-enabled the pickle serializer, so that Celery 4 works with this project.
