### ISSUE TITLE
Requirements compilation issue uWSGI 2.0.12 + fix

### ISSUE THREAD

**Issue by rliessum** [miguelgrinberg/flack#8]
On Ubuntu 17.04 (4.10.0-21-generic/gcc-6) installing the requirements gives a compiling error.
This can be fixed by using uWSGI==2.0.**13** in place of uWSGI==2.0.**12**

Error:
*** uWSGI compiling server core ***
--
    [thread 0][x86_64-linux-gnu-gcc -pthread] plugins/http/http.o
    plugins/corerouter/cr_map.c: In function ‘uwsgi_cr_map_use_static_nodes’:
    plugins/corerouter/cr_map.c:156:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
         if (!next_node)
         ^~
    plugins/corerouter/cr_map.c:159:6: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
          while (tmp_node != next_node) {
          ^~~~~
    [thread 4][x86_64-linux-gnu-gcc -pthread] plugins/http/keepalive.o
    cc1: all warnings being treated as errors

**Comment by miguelgrinberg** [comment]
@rliessum Thanks. Were you planning to submit a pull request with the fix, or do you prefer that I fix this myself?

**Comment by rliessum** [comment]
I created a pull request so if you are ok with it you can merge it.
